# Generated by Django 4.1.5 on 2023-01-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_language_alter_city_options_alter_city_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
